"""
Strict Mode service — document-grounded answers with exact locations
and Google search keyword suggestions generated by Gemini.
"""
import logging
import json
from typing import List, Dict, Any, Optional
from ..config import config

logger = logging.getLogger(__name__)


def _call_gemini_keywords(query: str, chunks: List[Dict[str, Any]]) -> List[str]:
    """Use Gemini to generate relevant Google search keywords from matched content."""
    try:
        from google import genai
        client = genai.Client(api_key=config.GEMINI_API_KEY)

        # Build context from top chunks
        context_parts = []
        for c in chunks[:4]:
            text = c.get("text", "")[:300]
            meta = c.get("metadata", {})
            doc = meta.get("document_name", "")
            context_parts.append(f"[{doc}]: {text}")
        context = "\n\n".join(context_parts)

        prompt = f"""You are a research assistant. Based on the user query and matching document excerpts below, generate 5 highly relevant Google search keyword phrases that would help someone find more information, related research, legal references, or academic papers about this topic.

User Query: {query}

Matching document content:
{context}

Rules:
- Generate exactly 5 search phrases
- Make them specific and useful for research
- Include terms like site:, filetype:pdf, or quotes "" where useful
- Return ONLY a valid JSON array of strings, no explanation

Example output: ["neural network training survey", "deep learning classification site:arxiv.org", "\"machine learning\" healthcare research 2024"]

Your JSON array:"""

        response = client.models.generate_content(
            model=config.GEMINI_MODEL,
            contents=prompt,
        )
        text = response.text.strip()

        # Parse JSON array from response
        start = text.find("[")
        end = text.rfind("]") + 1
        if start != -1 and end > start:
            keywords = json.loads(text[start:end])
            if isinstance(keywords, list):
                return [str(k) for k in keywords[:6]]

        logger.warning("Could not parse Gemini keyword response, using fallback")
        return _fallback_keywords(query)

    except Exception as e:
        logger.error(f"Gemini keyword generation failed: {e}")
        return _fallback_keywords(query)


def _fallback_keywords(query: str) -> List[str]:
    """Simple fallback keyword suggestions if Gemini is unavailable."""
    words = [w for w in query.split() if len(w) > 3][:4]
    base = " ".join(words)
    return [
        f"{base} research paper",
        f"{base} site:arxiv.org",
        f'"{base}" filetype:pdf',
        f"{base} academic journal",
        f"{base} explained",
    ]


def build_strict_response(
    query: str,
    reranked_results: List[Dict[str, Any]],
    processing_time_ms: float,
) -> Dict[str, Any]:
    """
    Build a Strict Mode response with:
    - Exact document locations (document name, page, chunk position)
    - Matched text excerpts
    - Google search keyword suggestions
    """
    # Enrich each result with a human-readable location string
    enriched = []
    for r in reranked_results:
        meta = r.get("metadata", {})
        page = meta.get("page_number") or meta.get("page")
        chunk_idx = meta.get("chunk_index")
        total_chunks = meta.get("total_chunks")

        location_parts = []
        if page:
            location_parts.append(f"Page {page}")
        if chunk_idx is not None and total_chunks:
            location_parts.append(f"Section {chunk_idx + 1} of {total_chunks}")
        elif chunk_idx is not None:
            location_parts.append(f"Chunk {chunk_idx}")

        enriched.append({
            "id": r.get("id", ""),
            "score": round(r.get("score", 0.0), 4),
            "rerank_score": round(r.get("rerank_score", 0.0), 4) if r.get("rerank_score") is not None else None,
            "text": r.get("text", ""),
            "document_name": meta.get("document_name", "Unknown Document"),
            "page": page,
            "chunk_index": chunk_idx,
            "total_chunks": total_chunks,
            "location": ", ".join(location_parts) if location_parts else "Document excerpt",
            "domain": meta.get("domain", ""),
        })

    # Generate Google search keywords using Gemini
    search_keywords = []
    if config.GEMINI_API_KEY and reranked_results:
        search_keywords = _call_gemini_keywords(query, reranked_results)

    return {
        "mode": "strict",
        "query": query,
        "results": enriched,
        "total_results": len(enriched),
        "search_keywords": search_keywords,
        "processing_time_ms": round(processing_time_ms, 2),
    }
